import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getNotifications,markAllNotificationsRead,markNotificationRead } from "../../../../api/notificationApi";
import "./Notifications.css";

const presentation={ENROLLED:["fa-user-plus","purple"],STEP_COMPLETED:["fa-check","green"],CHALLENGE_ASSIGNED:["fa-flag","orange"],CHALLENGE_SUBMITTED:["fa-star","orange"],CHALLENGE_GRADED:["fa-award","green"],CALENDAR_EVENT:["fa-calendar","blue"]};
const ago=(value)=>{const minutes=Math.max(0,Math.floor((Date.now()-new Date(value))/60000));if(minutes<1)return"now";if(minutes<60)return`${minutes}m`;const hours=Math.floor(minutes/60);if(hours<24)return`${hours}h`;return`${Math.floor(hours/24)}d`;};

export default function Notifications({isNotificationOpen,setIsNotificationOpen,darkmode,onCountChange}){
  const navigate=useNavigate();const [activeTab,setActiveTab]=useState("all");const [items,setItems]=useState([]);const [unreadCount,setUnreadCount]=useState(0);const [loading,setLoading]=useState(false);
  const load=()=>{setLoading(true);getNotifications(activeTab==="unread").then(data=>{setItems(data.notifications||[]);setUnreadCount(data.unreadCount||0);onCountChange?.(data.unreadCount||0)}).finally(()=>setLoading(false));};
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(isNotificationOpen)load()},[isNotificationOpen,activeTab]);
  async function open(item){if(!item.read_at){await markNotificationRead(item.id);setUnreadCount(value=>Math.max(0,value-1));onCountChange?.(Math.max(0,unreadCount-1));}setIsNotificationOpen(false);if(item.action_url)navigate(item.action_url)}
  async function markAll(){await markAllNotificationsRead();setItems(current=>current.map(item=>({...item,read_at:item.read_at||new Date().toISOString()})));setUnreadCount(0);onCountChange?.(0)}
  return <div className={`notifications ${isNotificationOpen?"open_notif":""} ${darkmode?"dark_notif":""}`}><div className="notifications_first"><p>My Notifications</p><i className="fa-solid fa-x" onClick={()=>setIsNotificationOpen(false)}/></div><div className="notifications_tabs"><button className={activeTab==="all"?"active":""} onClick={()=>setActiveTab("all")}>All</button><button className={activeTab==="unread"?"active":""} onClick={()=>setActiveTab("unread")}>Unread <span>{unreadCount}</span></button></div><div className="notifications_list">{loading?<div className="notifications_empty">Loading…</div>:items.length?items.map(item=>{const [icon,color]=presentation[item.notification_type]||["fa-bell","purple"];return <button type="button" className={`notification_card ${!item.read_at?"unread":""}`} key={item.id} onClick={()=>open(item)}><div className={`notification_icon ${color}`}><i className={`fa-solid ${icon}`}/></div><div className="notification_content"><strong>{item.title}</strong><span>{item.body}</span></div><div className="notification_meta"><small>{ago(item.created_at)}</small>{!item.read_at&&<div className="notification_dot"/>}</div></button>}):<div className="notifications_empty"><i className="fa-regular fa-bell"/><strong>No notifications here</strong><span>You&apos;re all caught up.</span></div>}</div><div className="notifications_footer"><button onClick={()=>navigate("/student/notifications")}><i className="fa-solid fa-gear"/>Notification settings</button><button className="mark_read" onClick={markAll}>Mark all as read</button></div></div>;
}
