const pool=require("../config/db"),journeyAccess=require("./journeyAccessService"),stageService=require("./stageService"),stepService=require("./stepService"),aiContent=require("./aiContentService"),{parseJsonPayload}=require("../utils/jsonPayload");const{openai}=aiContent;
const httpError=(message,statusCode)=>Object.assign(new Error(message),{statusCode});
const schema={
  type:"object",additionalProperties:false,required:["title","strategy","stages"],
  properties:{
    title:{type:"string"},strategy:{type:"string"},
    stages:{type:"array",minItems:1,maxItems:12,items:{
      type:"object",additionalProperties:false,required:["existingStageId","title","description","reason","steps"],
      properties:{
        existingStageId:{anyOf:[{type:"string"},{type:"null"}]},title:{type:"string"},description:{type:"string"},reason:{type:"string"},
        steps:{type:"array",minItems:1,maxItems:15,items:{
          type:"object",additionalProperties:false,required:["title","description","objective","reason","estimatedMinutes"],
          properties:{title:{type:"string"},description:{type:"string"},objective:{type:"string"},reason:{type:"string"},estimatedMinutes:{type:"integer",minimum:5,maximum:240}}
        }}
      }
    }}
  }
};
async function context(userId,journeyId){await journeyAccess.requireAccess(userId,journeyId,"EDIT");const journey=(await pool.query("SELECT id,title,description,difficulty,language,estimated_minutes FROM learning_journeys WHERE id=$1 AND status<>'ARCHIVED'",[journeyId])).rows[0];if(!journey)throw httpError("Learning Journey not found",404);const rows=(await pool.query(`SELECT stage.id stage_id,stage.title stage_title,stage.description stage_description,stage.position stage_position,step.id step_id,step.title step_title,step.description step_description,step.estimated_minutes,(SELECT jsonb_agg(jsonb_build_object('type',block.block_type,'content',block.content) ORDER BY block.position) FROM step_blocks block WHERE block.step_id=step.id) blocks FROM stages stage LEFT JOIN steps step ON step.stage_id=stage.id AND step.status<>'ARCHIVED' WHERE stage.learning_journey_id=$1 ORDER BY stage.position,step.position`,[journeyId])).rows;return{journey,rows}}
async function generate(userId,journeyId,input={}){const data=await context(userId,journeyId),prompt=String(input.prompt||"").trim();if(!prompt)throw httpError("Describe the course goal or the structure you need",400);const current=JSON.stringify(data.rows).slice(0,100000);const response=await openai("/responses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_CONTENT_MODEL||"gpt-4.1-mini",input:[{role:"user",content:[{type:"input_text",text:`Act as an instructional designer. Improve the Learning Journey "${data.journey.title}". Educator goal: ${prompt}. Metadata: ${JSON.stringify(data.journey)}. Current Stages, Steps and content: ${current}. Reuse an existing Stage by returning its exact stage_id in existingStageId. Propose only missing Steps and do not duplicate current topics. Create a coherent class sequence with measurable objectives, realistic duration, prerequisites and practice progression. Explain why every Stage and Step belongs. Output in ${input.language||data.journey.language||"English"}.`}]}],text:{format:{type:"json_schema",name:"journey_architecture",strict:true,schema}}})});const raw=response.output_text||response.output?.flatMap(item=>item.content||[]).find(item=>item.type==="output_text")?.text;if(!raw)throw httpError("The AI returned no Journey plan",502);return parseJsonPayload(raw,"AI Journey response",value=>Array.isArray(value?.stages))}
async function apply(userId,journeyId,{stages,generateContent=false,language="English"}={}){const data=await context(userId,journeyId);if(!Array.isArray(stages)||!stages.length||stages.length>12)throw httpError("Select at least one proposed Stage",400);const requestedSteps=stages.reduce((sum,stage)=>sum+(stage.steps?.length||0),0);if(requestedSteps>60)throw httpError("Apply at most 60 Steps at a time",400);if(generateContent&&requestedSteps>12)throw httpError("Generate full content for at most 12 Steps at a time. Select fewer Stages or create the remaining structure without content first.",400);if(generateContent&&!process.env.OPENAI_API_KEY)throw httpError("OPENAI_API_KEY is not configured",503);const existingIds=new Set(data.rows.map(row=>row.stage_id)),createdStages=[],createdSteps=[],contentFailures=[];for(const proposal of stages){let stageId=proposal.existingStageId;if(stageId&&!existingIds.has(stageId))throw httpError("The proposed existing Stage is invalid",400);if(!stageId){const created=await stageService.createStage(userId,journeyId,{title:proposal.title,description:proposal.description});stageId=created.id;createdStages.push(created)}for(const step of proposal.steps||[]){const duplicate=(await pool.query("SELECT 1 FROM steps WHERE stage_id=$1 AND status<>'ARCHIVED' AND LOWER(title)=LOWER($2) LIMIT 1",[stageId,step.title])).rows[0];if(duplicate)continue;const created=await stepService.createStep(userId,stageId,{title:step.title,description:[step.description,step.objective&&`Objective: ${step.objective}`,step.reason&&`AI rationale: ${step.reason}`].filter(Boolean).join("\n\n"),status:"DRAFT",estimatedMinutes:Number(step.estimatedMinutes)||null,isPreview:false,icon:"fa-wand-magic-sparkles",color:"purple"});createdSteps.push(created);if(generateContent){try{const draft=await aiContent.generate(userId,created.id,{language,prompt:`Write the complete editable lesson for this class. Journey: ${data.journey.title}. Stage: ${proposal.title}. Step description: ${step.description}. Learning objective: ${step.objective}. Instructional rationale: ${step.reason}. Include a clear explanation, examples and meaningful practice appropriate for the objective.`});await aiContent.apply(userId,created.id,draft.blocks)}catch(error){contentFailures.push({stepId:created.id,title:created.title,message:error.message})}}}}return{stages:createdStages,steps:createdSteps,contentGenerated:generateContent,contentFailures}}
module.exports={generate,apply};
