const stripe=require("../config/stripe"),pool=require("../config/db");
const feePercent=Number(process.env.STRIPE_PLATFORM_FEE_PERCENT||5);
async function user(userId){return(await pool.query("SELECT id,email,first_name,last_name,stripe_connected_account_id,connect_details_submitted,connect_charges_enabled,connect_payouts_enabled,connect_country FROM users WHERE id=$1",[userId])).rows[0]}
async function status(userId){const row=await user(userId);if(!row)return null;if(!row.stripe_connected_account_id)return{connected:false};const account=await stripe.accounts.retrieve(row.stripe_connected_account_id);await syncAccount(account);return{connected:true,accountId:account.id,detailsSubmitted:account.details_submitted,chargesEnabled:account.charges_enabled,payoutsEnabled:account.payouts_enabled,country:account.country,requirements:account.requirements?.currently_due||[]}}
async function onboarding(userId){let row=await user(userId),accountId=row.stripe_connected_account_id;if(!accountId){const account=await stripe.accounts.create({type:"express",email:row.email,business_type:"individual",capabilities:{card_payments:{requested:true},transfers:{requested:true}},business_profile:{product_description:"Online education and private classes through Maze Studio"},metadata:{mazeStudioUserId:userId}});accountId=account.id;await pool.query("UPDATE users SET stripe_connected_account_id=$1,connect_country=$2 WHERE id=$3",[accountId,account.country,userId])}const base=process.env.FRONTEND_URL.replace(/\/+$/,"");const link=await stripe.accountLinks.create({account:accountId,refresh_url:`${base}/my-settings/billing?connect=refresh`,return_url:`${base}/my-settings/billing?connect=return`,type:"account_onboarding"});return{url:link.url}}
async function dashboard(userId){const row=await user(userId);if(!row?.stripe_connected_account_id)throw Object.assign(new Error("Connect your payout account first"),{statusCode:400});return{url:(await stripe.accounts.createLoginLink(row.stripe_connected_account_id)).url}}
async function syncAccount(account){const userId=account.metadata?.mazeStudioUserId;await pool.query(`UPDATE users SET connect_details_submitted=$1,connect_charges_enabled=$2,connect_payouts_enabled=$3,connect_country=$4,updated_at=NOW() WHERE ${userId?"id=$5::uuid":"stripe_connected_account_id=$5"}`,[account.details_submitted,account.charges_enabled,account.payouts_enabled,account.country,userId||account.id])}
async function destinationForEducator(userId){const row=await user(userId);if(!row?.stripe_connected_account_id||!row.connect_charges_enabled||!row.connect_payouts_enabled)throw Object.assign(new Error("This educator must finish Stripe payout onboarding before accepting paid enrollments"),{statusCode:409});return{accountId:row.stripe_connected_account_id,feePercent}}
module.exports={status,onboarding,dashboard,syncAccount,destinationForEducator,feePercent};
