const pool=require("../config/db");
const httpError=(message,statusCode)=>Object.assign(new Error(message),{statusCode});
async function eligibility(userId,journeyId){return(await pool.query(`SELECT orders.id order_id,offering.owner_user_id educator_id,
  EXISTS(SELECT 1 FROM calendar_events event JOIN calendar_event_attendees attendee ON attendee.event_id=event.id JOIN learner_profiles profile ON profile.id=attendee.learner_profile_id WHERE event.metadata->>'offeringOrderId'=orders.id::text AND profile.linked_user_id=$1::uuid AND attendee.response_status='ATTENDED') attended
 FROM offering_orders orders JOIN offerings offering ON offering.id=orders.offering_id
 WHERE orders.learner_user_id=$1::uuid AND offering.learning_journey_id=$2::uuid AND orders.status IN('PAID','FREE') ORDER BY orders.created_at DESC LIMIT 1`,[userId,journeyId])).rows[0]}
function validate(input){const rating=Number(input.rating),comment=String(input.comment||"").trim();if(!Number.isInteger(rating)||rating<1||rating>5)throw httpError("Choose a rating from 1 to 5",400);if(comment.length>2000)throw httpError("Review comments are limited to 2000 characters",400);return{rating,comment:comment||null}}
async function save(userId,journeyId,input){const eligible=await eligibility(userId,journeyId);if(!eligible)throw httpError("Only verified learners who purchased this course can review it",403);const data=validate(input),kind=input.kind==="EDUCATOR"?"EDUCATOR":"COURSE";if(kind==="EDUCATOR"&&!eligible.attended)throw httpError("Confirm at least one completed class before reviewing the educator",403);const query=kind==="EDUCATOR"?`INSERT INTO educator_reviews(educator_user_id,learner_user_id,offering_order_id,rating,comment) VALUES($1,$2,$3,$4,$5) ON CONFLICT(educator_user_id,learner_user_id) DO UPDATE SET rating=EXCLUDED.rating,comment=EXCLUDED.comment,offering_order_id=EXCLUDED.offering_order_id,updated_at=NOW() RETURNING *`:`INSERT INTO learning_journey_reviews(learning_journey_id,learner_user_id,offering_order_id,rating,comment) VALUES($1,$2,$3,$4,$5) ON CONFLICT(learning_journey_id,learner_user_id) DO UPDATE SET rating=EXCLUDED.rating,comment=EXCLUDED.comment,offering_order_id=EXCLUDED.offering_order_id,updated_at=NOW() RETURNING *`;return(await pool.query(query,[kind==="EDUCATOR"?eligible.educator_id:journeyId,userId,eligible.order_id,data.rating,data.comment])).rows[0]}
async function journey(journeyId,userId=null){const [summary,reviews,mine,eligible]=await Promise.all([pool.query("SELECT COALESCE(ROUND(AVG(rating)::numeric,1),0) average,COUNT(*)::int count FROM learning_journey_reviews WHERE learning_journey_id=$1",[journeyId]),pool.query(`SELECT review.rating,review.comment,review.updated_at,CONCAT_WS(' ',student.first_name,student.last_name) learner_name FROM learning_journey_reviews review JOIN users student ON student.id=review.learner_user_id WHERE review.learning_journey_id=$1 AND review.comment IS NOT NULL ORDER BY review.updated_at DESC LIMIT 20`,[journeyId]),userId?pool.query("SELECT rating,comment FROM learning_journey_reviews WHERE learning_journey_id=$1 AND learner_user_id=$2",[journeyId,userId]):Promise.resolve({rows:[]}),userId?eligibility(userId,journeyId):null]);return{summary:summary.rows[0],reviews:reviews.rows,mine:mine.rows[0]||null,canReviewCourse:Boolean(eligible),canReviewEducator:Boolean(eligible?.attended)}}
async function educator(educatorId){const [summary,reviews]=await Promise.all([pool.query("SELECT COALESCE(ROUND(AVG(rating)::numeric,1),0) average,COUNT(*)::int count FROM educator_reviews WHERE educator_user_id=$1",[educatorId]),pool.query(`SELECT review.rating,review.comment,review.updated_at,CONCAT_WS(' ',student.first_name,student.last_name) learner_name FROM educator_reviews review JOIN users student ON student.id=review.learner_user_id WHERE review.educator_user_id=$1 AND review.comment IS NOT NULL ORDER BY review.updated_at DESC LIMIT 20`,[educatorId])]);return{summary:summary.rows[0],reviews:reviews.rows}}
module.exports={save,journey,educator};
