import {useEffect,useMemo,useState} from "react";
import {Link,useNavigate,useParams,useSearchParams} from "react-router-dom";
import {apiRequest} from "../../../api/api";
import PrivateBookingCalendar from "./PrivateBookingCalendar";
import "./Marketplace.css";
import { useAuth } from "../../../context/AuthContext";
import "./PrivateBookingCalendar.css";
import "./PrivateBookingSlots.css";
import "./SubscriptionNotice.css";
import "./EducatorProfileLink.css";
import CourseCurriculum from "./CourseCurriculum";
const labels={SELF_PACED:"Learn at your own pace",ONE_TO_ONE:"Private 1:1 classes",COHORT:"Join a live group",WEBINAR:"Attend the webinar",HYBRID:"Hybrid experience"};
const icons={SELF_PACED:"fa-play",ONE_TO_ONE:"fa-user-group",COHORT:"fa-people-group",WEBINAR:"fa-video",HYBRID:"fa-shuffle"};
const money=(amount,currency)=>amount===0?"Free":new Intl.NumberFormat(undefined,{style:"currency",currency}).format(amount/100);

export default function MarketplaceOffer(){
 const {user}=useAuth();
 const {journeyId}=useParams(),navigate=useNavigate();const [params]=useSearchParams();
 const [data,setData]=useState(null),[experienceId,setExperienceId]=useState(""),[cohortId,setCohortId]=useState(""),[classCount,setClassCount]=useState(1),[calendarBooking,setCalendarBooking]=useState({frequency:"CUSTOM",sessionDates:[],valid:false}),[availability,setAvailability]=useState({slots:[],educatorTimezone:null}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{apiRequest(`/marketplace/journeys/${journeyId}`).then(result=>{setData(result);if(result.experiences?.length)setExperienceId(result.experiences[0].id)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[journeyId]);
 useEffect(()=>{const sessionId=params.get("session_id");if(params.get("checkout")!=="success"||!sessionId)return;setBusy(true);apiRequest("/marketplace/checkout/confirm",{method:"POST",body:JSON.stringify({sessionId})}).then(result=>result.enrolled?navigate(result.redirectUrl||"/my-learning",{replace:true}):setError("Your payment is still being confirmed.")).catch(e=>setError(e.message)).finally(()=>setBusy(false))},[params,navigate]);
 const experience=useMemo(()=>data?.experiences.find(item=>item.id===experienceId)||null,[data,experienceId]);
 const isPrivate=experience?.offering_type==="ONE_TO_ONE",needsGroup=["COHORT","HYBRID","WEBINAR"].includes(experience?.offering_type);
 useEffect(()=>{setCohortId(experience?.cohorts?.length===1?experience.cohorts[0].id:"");setClassCount(1);setCalendarBooking({frequency:"CUSTOM",sessionDates:[],valid:false})},[experienceId]);
 useEffect(()=>{if(!isPrivate){setAvailability({slots:[],educatorTimezone:null});return}const from=new Date().toISOString(),to=new Date(Date.now()+730*86400000).toISOString();apiRequest(`/marketplace/offerings/${experience.id}/availability?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`).then(result=>setAvailability({slots:result.slots||[],educatorTimezone:result.educatorTimezone||null})).catch(()=>setAvailability({slots:[],educatorTimezone:null}))},[isPrivate,experience?.id]);
 const monthly=isPrivate&&calendarBooking.frequency==="WEEKLY";
 const total=experience?experience.price_amount*(isPrivate?classCount*(monthly?4:1):1):0;
 async function enroll(){if(!user){navigate(`/login?returnTo=${encodeURIComponent(`/marketplace/journeys/${journeyId}`)}`);return}setBusy(true);setError("");try{const result=await apiRequest(`/marketplace/offerings/${experience.id}/enroll`,{method:"POST",body:JSON.stringify({cohortId:cohortId||null,booking:isPrivate?{sessionCount:classCount,frequency:calendarBooking.frequency,sessionDates:calendarBooking.sessionDates,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone}:undefined})});if(result.checkoutUrl)window.location.assign(result.checkoutUrl);else navigate(result.redirectUrl||"/my-learning")}catch(e){setError(e.message);setBusy(false)}}
 if(loading)return <div className="marketplace_status"><i className="fa-solid fa-spinner fa-spin"/> Loading course preview…</div>;
 if(!data)return <section className="student_empty_state"><h2>Course unavailable</h2><p>{error}</p><Link to="/marketplace">Back to Marketplace</Link></section>;
 const {journey,experiences}=data;
 return <div className="offer_detail_page"><Link className="offer_back" to="/marketplace"><i className="fa-solid fa-arrow-left"/> Marketplace</Link><section className="course_preview_hero"><div>{journey.cover_url?<img src={journey.cover_url} alt=""/>:<i className="fa-solid fa-route"/>}</div><main><span className="student_section_kicker">Course preview</span><h1>{journey.title}</h1><p>{journey.description||"Explore the course and choose the experience that fits you best."}</p><Link className="offer_educator" to={`/educators/${journey.educator_slug||journey.educator_id}`}>{journey.educator_avatar_url?<img src={journey.educator_avatar_url} alt=""/>:<i className="fa-solid fa-user-graduate"/>}<span>Created by <strong>{journey.educator_name}</strong><small>View educator profile</small></span></Link></main></section>
 <section className="course_preview_body"><main><span className="student_section_kicker">Course overview</span><h2>What this Learning Journey includes</h2><p>{journey.description||"Structured content, guided activities and progress tracking."}</p><div className="offer_facts"><span><i className="fa-solid fa-signal"/><b>{journey.difficulty||"All levels"}</b><small>Difficulty</small></span><span><i className="fa-solid fa-language"/><b>{journey.language||"Not specified"}</b><small>Language</small></span><span><i className="fa-regular fa-clock"/><b>{journey.estimated_minutes?`${journey.estimated_minutes} min`:"Flexible"}</b><small>Content</small></span></div></main>
 <aside className="experience_picker"><span className="student_section_kicker">Choose your experience</span><h2>How do you want to learn?</h2><div className="experience_options">{experiences.map(item=><button className={experienceId===item.id?"selected":""} onClick={()=>setExperienceId(item.id)} key={item.id}><i className={`fa-solid ${icons[item.offering_type]}`}/><span><strong>{item.title}</strong><small>{labels[item.offering_type]}</small></span><b>{item.offering_type==="ONE_TO_ONE"?`${money(item.price_amount,item.currency)} / class`:money(item.price_amount,item.currency)}</b></button>)}</div>
 {experience&&<div className="experience_configuration"><h3>{experience.title}</h3><p>{experience.description||labels[experience.offering_type]}</p>{needsGroup&&<div className="offer_groups"><strong>Choose an available group</strong>{experience.cohorts.length?experience.cohorts.map(group=><label className={cohortId===group.id?"selected":""} key={group.id}><input type="radio" checked={cohortId===group.id} onChange={()=>setCohortId(group.id)}/><span><strong>{group.title}</strong><small>{group.starts_at?new Date(group.starts_at).toLocaleDateString(undefined,{dateStyle:"long"}):"Date to be announced"} · {group.capacity-group.member_count} seats left</small></span></label>):<div className="offer_no_groups">No open groups have seats available.</div>}</div>}
 {isPrivate&&<div className="private_booking_flow"><section className="package_picker"><header><span><b>1</b><strong>Choose your package</strong></span><small>{money(experience.price_amount,experience.currency)} per {experience.session_duration_minutes}-minute class</small></header><div>{[1,4,8,12].map(count=><button type="button" className={classCount===count?"active":""} onClick={()=>setClassCount(count)} key={count}><strong>{count}</strong><span>{count===1?"class":"classes"}</span></button>)}</div><label>Custom amount <input type="number" min="1" max="52" value={classCount} onChange={e=>setClassCount(Math.min(52,Math.max(1,Number(e.target.value)||1)))}/></label></section><section className="calendar_step_title"><b>2</b><span><strong>Schedule your classes</strong><small>Only hours offered by the educator are shown.</small></span></section><PrivateBookingCalendar count={classCount} duration={Number(experience.session_duration_minutes)||60} availableSlots={availability.slots} educatorTimezone={availability.educatorTimezone} onChange={setCalendarBooking}/></div>}
 <footer><span><small>{monthly?`${classCount} ${classCount===1?"class":"classes"} weekly · billed monthly`:"Total"}</small><strong>{money(total,experience.currency)}{monthly&&<small> / month</small>}</strong></span>{experience.purchased&&!monthly?<button onClick={()=>navigate(`/learn/journeys/${journey.id}`)}>Already purchased · Continue</button>:<button disabled={busy||(needsGroup&&!cohortId)||(isPrivate&&!calendarBooking.valid)} onClick={enroll}>{busy?<><i className="fa-solid fa-spinner fa-spin"/> Processing…</>:total===0?"Enroll for free":monthly?"Start monthly subscription":"Continue to payment"}</button>}</footer>{monthly&&<div className="subscription_notice"><i className="fa-solid fa-arrows-rotate"/><span><strong>Renews every month until cancelled</strong><small>The monthly price includes four weeks. Your selected {classCount===1?"class repeats":"classes repeat"} every week.</small></span></div>}{isPrivate&&!availability.slots.length&&<div className="offer_error"><i className="fa-solid fa-calendar-xmark"/> The educator has not published available hours yet.</div>}{error&&<div className="offer_error">{error}</div>}</div>}</aside></section><CourseCurriculum journeyId={journey.id} stages={data.structure||[]}/></div>;
}
