import {useEffect,useMemo,useState} from "react";
const pad=value=>String(value).padStart(2,"0"),key=date=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`,DAYS=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
export default function PrivateBookingCalendar({count,duration,availableSlots,educatorTimezone,onChange}){
 const [cursor,setCursor]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[mode,setMode]=useState("CUSTOM"),[focusedDay,setFocusedDay]=useState(""),[selected,setSelected]=useState([]);
 const learnerTimezone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 useEffect(()=>{setSelected(current=>current.filter(value=>availableSlots.includes(value)).slice(0,count))},[count,availableSlots.join("|")]);
 const slotsByDay=useMemo(()=>availableSlots.reduce((map,value)=>{const day=key(new Date(value));(map[day]??=[]).push(value);return map},{}),[availableSlots]);
 const monthDays=useMemo(()=>{const start=new Date(cursor.getFullYear(),cursor.getMonth(),1);start.setDate(1-start.getDay());return Array.from({length:42},(_,index)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+index))},[cursor]);
 useEffect(()=>onChange({frequency:mode,sessionDates:selected.slice().sort(),valid:selected.length===count}),[mode,selected.join("|"),count,onChange]);
 function selectSlot(value){setSelected(current=>current.includes(value)?current.filter(item=>item!==value):current.length<count?[...current,value]:current)}
 const daySlots=slotsByDay[focusedDay]||[];
 return <div className="booking_calendar"><header><div><span>Schedule style</span><strong>Choose from the educator's available times</strong></div><div className="booking_mode"><button type="button" className={mode==="CUSTOM"?"active":""} onClick={()=>{setMode("CUSTOM");setSelected([])}}><i className="fa-solid fa-calendar-days"/> Different dates</button><button type="button" className={mode==="WEEKLY"?"active":""} onClick={()=>{setMode("WEEKLY");setSelected([])}}><i className="fa-solid fa-repeat"/> Same time weekly</button></div></header><div className="timezone_conversion"><i className="fa-solid fa-earth-americas"/><span><strong>Times are shown in {learnerTimezone}</strong><small>Educator availability: {educatorTimezone||"timezone not specified"}. Conversion is automatic.</small></span></div>
 <section className="booking_month"><header><button type="button" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><i className="fa-solid fa-chevron-left"/></button><strong>{cursor.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</strong><button type="button" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><i className="fa-solid fa-chevron-right"/></button></header><div className="booking_weekdays">{DAYS.map(day=><span key={day}>{day.slice(0,2)}</span>)}</div><div className="booking_month_days">{monthDays.map(date=>{const value=key(date),hasSlots=Boolean(slotsByDay[value]?.length),selectedDay=selected.some(slot=>key(new Date(slot))===value);return <button type="button" disabled={!hasSlots} className={`${date.getMonth()!==cursor.getMonth()?"outside":""} ${focusedDay===value?"focused":""} ${selectedDay?"selected":""}`} onClick={()=>setFocusedDay(value)} key={value}><span>{date.getDate()}</span>{hasSlots&&<i/>}</button>})}</div></section>
 {focusedDay&&<section className="available_times"><header><span>Available on</span><strong>{new Date(`${focusedDay}T12:00:00`).toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</strong></header>{daySlots.length?<div>{daySlots.map(value=><button type="button" className={selected.includes(value)?"selected":""} onClick={()=>selectSlot(value)} key={value}>{new Date(value).toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"})}</button>)}</div>:<p>No available hours on this day.</p>}{mode==="WEEKLY"&&<small>Choose {count} different weekly {count===1?"time":"times"}. Every selected weekday and time will repeat each week.</small>}</section>}
 <footer><span><strong>{selected.length} of {count}</strong> {mode==="WEEKLY"?"weekly class times":"classes scheduled"}</span><div className="booking_progress"><i style={{width:`${Math.min(100,selected.length/count*100)}%`}}/></div>{mode==="WEEKLY"&&selected.length<count&&<small>Select {count-selected.length} more weekly {count-selected.length===1?"time":"times"}.</small>}</footer><p className="booking_calendar_note"><i className="fa-regular fa-clock"/> Each class lasts {duration} minutes.{mode==="WEEKLY"?" Your subscription repeats these classes every week.":""}</p></div>;
}
