import { useEffect, useRef, useState } from "react";
import MazeCanvasStage from "./MazeCanvasStage";
import { CANVAS_HEIGHT, CANVAS_WIDTH, normalizeCanvasDocument } from "./mazeCanvasDocument";
import "./CanvasDocumentViewer.css";
import "./CanvasViewerMobile.css";
import "./CanvasViewerPolish.css";
import "./CanvasViewerPages.css";

export default function CanvasDocumentViewer({document:source}){
  const document=normalizeCanvasDocument(source);
  const [index,setIndex]=useState(0);
  const [bounds,setBounds]=useState({width:900,height:520});
  const container=useRef(null);
  useEffect(()=>{const measure=()=>{const rect=container.current?.getBoundingClientRect();const fullscreen=window.document.fullscreenElement===container.current;setBounds({width:Math.min(CANVAS_WIDTH,Math.max(280,(rect?.width||900)-40)),height:Math.min(CANVAS_HEIGHT,Math.max(180,window.innerHeight*(fullscreen ? .72 : .5)))})};const observer=new ResizeObserver(measure);if(container.current)observer.observe(container.current);window.addEventListener("resize",measure);window.document.addEventListener("fullscreenchange",measure);measure();return()=>{observer.disconnect();window.removeEventListener("resize",measure);window.document.removeEventListener("fullscreenchange",measure)}},[]);
  useEffect(()=>{const keyboard=event=>{if(event.key==="ArrowLeft")setIndex(value=>Math.max(0,value-1));if(event.key==="ArrowRight")setIndex(value=>Math.min(document.pages.length-1,value+1))};window.addEventListener("keydown",keyboard);return()=>window.removeEventListener("keydown",keyboard)},[document.pages.length]);
  const page=document.pages[Math.min(index,document.pages.length-1)];const scale=Math.min(bounds.width/CANVAS_WIDTH,bounds.height/CANVAS_HEIGHT);const pageWidth=CANVAS_WIDTH*scale,pageHeight=CANVAS_HEIGHT*scale;
  return <section className="canvas_document_viewer" ref={container}><header className="canvas_viewer_heading"><div><span>PRESENTACIÓN</span><strong>{document.title}</strong></div><small>{index+1} de {document.pages.length}</small></header><nav className="canvas_viewer_page_strip" aria-label="Páginas de la presentación">{document.pages.map((item,position)=><button type="button" key={item.id} className={position===index?"active":""} onClick={()=>setIndex(position)}><span className="canvas_viewer_thumbnail"><MazeCanvasStage page={item} scale={.084} selectedId={null} onSelect={()=>{}} onElementChange={()=>{}} preview/></span><span className="canvas_viewer_page_meta"><small>{position+1}</small><strong>{item.name||`Página ${position+1}`}</strong></span></button>)}</nav><div className="canvas_current_page_title"><strong>{page.name||`Página ${index+1}`}</strong><span>Usa las páginas de arriba o las flechas del teclado</span></div><div className="canvas_presentation_frame"><div className="canvas_viewport" style={{width:pageWidth,height:pageHeight}}><MazeCanvasStage page={page} scale={scale} selectedId={null} onSelect={()=>{}} onElementChange={()=>{}} preview/>{page.elements.filter(item=>item.type==="VIDEO_EMBED"&&item.url).map(item=><video key={item.id} controls playsInline src={item.url} title={item.title||"Video"} style={{left:item.x*scale,top:item.y*scale,width:item.width*scale,height:item.height*scale,transform:`rotate(${item.rotation||0}deg)`}}/>)}</div></div><footer><button type="button" disabled={index===0} onClick={()=>setIndex(value=>value-1)}><i className="fa-solid fa-arrow-left"/> <span>Anterior</span></button><button type="button" className="canvas_fullscreen" onClick={()=>container.current?.requestFullscreen?.()} aria-label="Pantalla completa"><i className="fa-solid fa-expand"/><span>Pantalla completa</span></button><button type="button" disabled={index===document.pages.length-1} onClick={()=>setIndex(value=>value+1)}><span>Siguiente</span> <i className="fa-solid fa-arrow-right"/></button></footer></section>;
}
