const express = require("express");
const auth = require("../middlewares/authMiddleware");
const educatorOnly = require("../middlewares/educatorOnlyMiddleware");
const controller = require("../controllers/challengeController");
const blockAssetUpload = require("../middlewares/blockAssetUploadMiddleware");

const router = express.Router();
router.post("/challenges", auth, educatorOnly, controller.create);
router.get("/learning-journeys/:journeyId/challenges", auth, educatorOnly, controller.list);
router.get("/challenges/:challengeId", auth, educatorOnly, controller.get);
router.put("/challenges/:challengeId", auth, educatorOnly, controller.update);
router.delete("/challenges/:challengeId", auth, educatorOnly, controller.remove);
router.post("/challenges/:challengeId/steps", auth, educatorOnly, controller.attachStep);
router.delete("/challenges/:challengeId/steps/:stepId", auth, educatorOnly, controller.detachStep);
router.post("/challenges/:challengeId/blocks", auth, educatorOnly, controller.createBlock);
router.patch("/challenges/:challengeId/blocks/reorder", auth, educatorOnly, controller.reorderBlocks);
router.put("/challenge-blocks/:blockId", auth, educatorOnly, controller.updateBlock);
router.delete("/challenge-blocks/:blockId", auth, educatorOnly, controller.deleteBlock);
router.post("/challenge-blocks/:blockId/asset", auth, educatorOnly, blockAssetUpload.single("file"), controller.uploadBlockAsset);
router.get("/challenges/:challengeId/assignments", auth, educatorOnly, controller.assignments);
router.get("/challenges/:challengeId/assignable-learners", auth, educatorOnly, controller.assignableLearners);
router.post("/challenges/:challengeId/assignments", auth, educatorOnly, controller.assignLearner);
router.delete("/challenges/:challengeId/assignments/:enrollmentId", auth, educatorOnly, controller.revokeAssignment);
router.get("/challenges/:challengeId/attempts", auth, educatorOnly, controller.attempts);
router.get("/challenge-attempts/:attemptId", auth, educatorOnly, controller.attempt);
router.put("/challenge-attempts/:attemptId/review", auth, educatorOnly, controller.review);
router.post("/challenges/:challengeId/private-links", auth, educatorOnly, controller.createLink);
router.get("/challenges/:challengeId/private-links", auth, educatorOnly, controller.links);
router.patch("/challenge-private-links/:linkId", auth, educatorOnly, controller.updateLink);
router.delete("/challenge-private-links/:linkId", auth, educatorOnly, controller.revokeLink);
module.exports = router;
