import { useMemo, useState } from "react";
import "./CohortScheduleBuilder.css";

const pad=(value)=>String(value).padStart(2,"0");
const key=(date)=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;
const startOfWeek=(date)=>{const value=new Date(date);const day=value.getDay()||7;value.setDate(value.getDate()-day+1);value.setHours(12,0,0,0);return value};

export default function CohortScheduleBuilder({slots,weeks,frequency,timezone,onSlotsChange,onWeeksChange,onFrequencyChange}){
 const [cursor,setCursor]=useState(()=>startOfWeek(new Date(Date.now()+7*86400000))),[selectedDate,setSelectedDate]=useState(""),[time,setTime]=useState("18:00");
 const days=useMemo(()=>Array.from({length:7},(_,index)=>new Date(cursor.getFullYear(),cursor.getMonth(),cursor.getDate()+index,12)),[cursor]);
 function add(){if(!selectedDate||!time)return;const duplicate=slots.some(slot=>slot.firstDate===selectedDate&&slot.time===time);if(duplicate)return;const date=new Date(`${selectedDate}T12:00:00`);onSlotsChange([...slots,{id:crypto.randomUUID(),firstDate:selectedDate,day:date.getDay(),time}])}
 const interval=frequency==="BIWEEKLY"?2:1,total=slots.length*Number(weeks||0);
 return <div className="cohort_schedule_builder">
  <header><div><span>Weekly calendar</span><h4>Choose every recurring class time</h4><p>Select a date in the first teaching week, choose its time and add it. Add as many weekly meetings as this Cohort needs.</p></div><div className="cohort_timezone"><i className="fa-solid fa-earth-americas"/><span><small>Schedule timezone</small><strong>{timezone}</strong></span></div></header>
  <div className="cohort_week_nav"><button type="button" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth(),cursor.getDate()-7,12))}><i className="fa-solid fa-chevron-left"/></button><strong>{days[0].toLocaleDateString(undefined,{month:"short",day:"numeric"})} – {days[6].toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}</strong><button type="button" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth(),cursor.getDate()+7,12))}><i className="fa-solid fa-chevron-right"/></button></div>
  <div className="cohort_week_days">{days.map(date=>{const value=key(date),selected=selectedDate===value,hasSlot=slots.some(slot=>slot.firstDate===value);return <button type="button" className={`${selected?"selected":""} ${hasSlot?"has_slot":""}`} onClick={()=>setSelectedDate(value)} key={value}><small>{date.toLocaleDateString(undefined,{weekday:"short"})}</small><strong>{date.getDate()}</strong>{hasSlot&&<i/>}</button>})}</div>
  <div className="cohort_add_time"><div>{selectedDate?<><span>Class on</span><strong>{new Date(`${selectedDate}T12:00:00`).toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</strong></>:<><span>First choose a day</span><strong>Select it in the calendar above</strong></>}</div><label>Starts at<input type="time" value={time} onChange={event=>setTime(event.target.value)}/></label><button type="button" disabled={!selectedDate} onClick={add}><i className="fa-solid fa-plus"/> Add weekly time</button></div>
  <section className="cohort_selected_times"><header><span><strong>{slots.length}</strong> {slots.length===1?"class time":"class times"} every teaching week</span></header>{slots.length?<div>{slots.map(slot=><article key={slot.id}><i className="fa-regular fa-calendar-check"/><span><strong>{new Date(`${slot.firstDate}T${slot.time}`).toLocaleDateString(undefined,{weekday:"long"})} at {new Date(`${slot.firstDate}T${slot.time}`).toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"})}</strong><small>First class: {new Date(`${slot.firstDate}T${slot.time}`).toLocaleDateString(undefined,{month:"long",day:"numeric",year:"numeric"})}</small></span><button type="button" onClick={()=>onSlotsChange(slots.filter(item=>item.id!==slot.id))} aria-label="Remove class time"><i className="fa-solid fa-xmark"/></button></article>)}</div>:<div className="cohort_schedule_empty"><i className="fa-regular fa-calendar-plus"/><span><strong>No recurring times yet</strong><small>Add at least one day and time.</small></span></div>}</section>
  <div className="cohort_schedule_duration"><label>Repeat<select value={frequency} onChange={event=>onFrequencyChange(event.target.value)}><option value="WEEKLY">Every week</option><option value="BIWEEKLY">Every two weeks</option></select></label><label>For how many teaching weeks?<input type="number" min="1" max="104" value={weeks} onChange={event=>onWeeksChange(event.target.value)}/></label><div><span>Total scheduled classes</span><strong>{total}</strong><small>{slots.length} per teaching week × {Number(weeks||0)} teaching weeks{interval===2?" · every two weeks":""}</small></div></div>
 </div>;
}
