import {useEffect,useState} from "react";import {apiRequest} from "../../../../../api/api";
const ROLES={EDITOR:"Can edit Stages, Steps and content.",INSTRUCTOR:"Can manage Students, paths and reviews.",VIEWER:"Can inspect the Journey without making changes."};
export default function JourneyCollaborators({journeyId}){const[list,setList]=useState([]);const[email,setEmail]=useState("");const[role,setRole]=useState("EDITOR");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
async function load(){try{const d=await apiRequest(`/learning-journeys/${journeyId}/collaborators`);setList(d.collaborators||[])}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[journeyId]);
async function add(e){e.preventDefault();setSaving(true);setError("");setMessage("");try{const d=await apiRequest(`/learning-journeys/${journeyId}/collaborators`,{method:"POST",body:JSON.stringify({email,role})});setList(d.collaborators||[]);setEmail("");setMessage("Collaborator added successfully.")}catch(x){setError(x.message)}finally{setSaving(false)}}
async function change(id,next){try{const d=await apiRequest(`/learning-journeys/${journeyId}/collaborators/${id}`,{method:"PATCH",body:JSON.stringify({role:next})});setList(d.collaborators||[])}catch(x){setError(x.message)}}
async function remove(id){if(!window.confirm("Remove this collaborator from the Journey?"))return;try{const d=await apiRequest(`/learning-journeys/${journeyId}/collaborators/${id}`,{method:"DELETE"});setList(d.collaborators||[])}catch(x){setError(x.message)}}
return <section className="journey_collaborators"><header><div><span>Shared teaching</span><h2>Collaborators</h2><p>Invite subscribed educators to work on this Learning Journey.</p></div><div className="collaborator_subscription_note"><i className="fa-solid fa-shield-halved"/><span><strong>Educator plan required</strong>Access pauses automatically if their subscription becomes inactive.</span></div></header>
<form onSubmit={add}><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="teacher@example.com" required/></label><label>Permission<select value={role} onChange={e=>setRole(e.target.value)}>{Object.keys(ROLES).map(r=><option key={r} value={r}>{r[0]+r.slice(1).toLowerCase()}</option>)}</select></label><button disabled={saving}><i className="fa-solid fa-user-plus"/>{saving?"Adding…":"Add collaborator"}</button><p>{ROLES[role]}</p></form>
{error&&<div className="journey_students_alert error">{error}</div>}{message&&<div className="journey_students_alert success">{message}</div>}
{loading?<div className="journey_students_state">Loading collaborators…</div>:list.length===0?<div className="journey_students_state"><i className="fa-solid fa-people-group"/><h3>Only you are working here</h3><p>Add another subscribed educator when you are ready.</p></div>:<div className="collaborator_list">{list.map(c=>{const subscribed=["ACTIVE","TRIALING"].includes(String(c.subscription_status||"").toUpperCase());return <article key={c.id}><span className="collaborator_avatar">{(c.first_name?.[0]||c.email[0]).toUpperCase()}{c.last_name?.[0]?.toUpperCase()||""}</span><div><strong>{[c.first_name,c.last_name].filter(Boolean).join(" ")||c.email}</strong><small>{c.email}</small><em className={subscribed?"active":"inactive"}>{subscribed?"Subscription active":"Access paused"}</em></div><select value={c.role} onChange={e=>change(c.id,e.target.value)}>{Object.keys(ROLES).map(r=><option key={r} value={r}>{r[0]+r.slice(1).toLowerCase()}</option>)}</select><button onClick={()=>remove(c.id)} aria-label="Remove collaborator"><i className="fa-solid fa-trash"/></button></article>})}</div>}</section>}
