import {useEffect,useState} from "react";
import {apiRequest} from "../../../../../api/api";
import "./JourneyOfferings.css";
import "./JourneyOfferingEnhancements.css";
import "./TeacherAvailability.css";
import "./CommercialPolicies.css";
import CohortScheduleBuilder from "./CohortScheduleBuilder";

const TYPES={SELF_PACED:{icon:"fa-person-walking",label:"Self-paced",hint:"Students purchase permanent access and learn independently."},ONE_TO_ONE:{icon:"fa-user-group",label:"1:1 classes",hint:"Students choose how many private classes they need."},COHORT:{icon:"fa-people-group",label:"Cohort",hint:"Create one scheduled group with its dates and available seats."}};
const PAYMENTS={ONE_TIME:{label:"Complete payment",hint:"Charge the complete experience once."},MONTHLY:{label:"Monthly subscription",hint:"Charge every month until cancellation."},PER_SESSION:{label:"Charge per class",hint:"Each scheduled group class has its own charge."},FLEXIBLE:{label:"Student chooses",hint:"One-time package or monthly weekly classes."}};
const ACCESS={LIFETIME:{label:"Permanent access",hint:"Content remains available after classes end."},WHILE_ACTIVE:{label:"While payments are active",hint:"Content pauses when the subscription ends."},FIXED_DAYS:{label:"Limited number of days",hint:"Access expires after the configured period."}};
const WEEKDAYS=[[1,"Mon"],[2,"Tue"],[3,"Wed"],[4,"Thu"],[5,"Fri"],[6,"Sat"],[0,"Sun"]];
const localZone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;
const empty=()=>({title:"",description:"",offeringType:"SELF_PACED",priceAmount:"",currency:"MXN",paymentModel:"ONE_TIME",accessPolicy:"LIFETIME",accessDurationDays:"",sessionCount:"8",sessionDurationMinutes:"60",scheduleMode:"FLEXIBLE",capacity:"12",weekly:true,cohortStartsAt:"",cohortFrequency:"WEEKLY",cohortTimezone:localZone(),cohortWeeks:"8",cohortSlots:[],availabilityDays:[1,2,3,4,5],availabilityStart:"09:00",availabilityEnd:"17:00",availabilityTimezone:localZone()});
function fromItem(item){const availability=item.settings?.bookingAvailability,weekly=availability?.weekly||[],cohort=item.settings?.cohortConfiguration||{},legacyDate=cohort.firstStartsAt?new Date(cohort.firstStartsAt):null,legacySlot=legacyDate&&!Number.isNaN(legacyDate.getTime())?[{id:crypto.randomUUID(),firstDate:`${legacyDate.getFullYear()}-${String(legacyDate.getMonth()+1).padStart(2,"0")}-${String(legacyDate.getDate()).padStart(2,"0")}`,day:legacyDate.getDay(),time:`${String(legacyDate.getHours()).padStart(2,"0")}:${String(legacyDate.getMinutes()).padStart(2,"0")}`}]:[];return{...empty(),title:item.title||"",description:item.description||"",offeringType:item.offering_type,priceAmount:item.price_amount/100,currency:item.currency,paymentModel:item.payment_model||(item.offering_type==="ONE_TO_ONE"?"FLEXIBLE":"ONE_TIME"),accessPolicy:item.access_policy||"LIFETIME",accessDurationDays:item.access_duration_days||"",sessionCount:item.session_count||"8",sessionDurationMinutes:item.session_duration_minutes||"60",scheduleMode:item.schedule_mode||"FLEXIBLE",capacity:item.capacity||"12",weekly:item.recurrence_rule?.frequency==="WEEKLY",cohortStartsAt:cohort.firstStartsAt?new Date(new Date(cohort.firstStartsAt).getTime()-new Date(cohort.firstStartsAt).getTimezoneOffset()*60000).toISOString().slice(0,16):"",cohortFrequency:cohort.frequency||"WEEKLY",cohortTimezone:cohort.timezone||localZone(),cohortWeeks:cohort.weeks||"8",cohortSlots:cohort.slots?.length?cohort.slots:legacySlot,cohortId:cohort.cohortId||"",availabilityDays:weekly.length?[...new Set(weekly.map(rule=>Number(rule.day)))]:[1,2,3,4,5],availabilityStart:weekly[0]?.start||"09:00",availabilityEnd:weekly[0]?.end||"17:00",availabilityTimezone:availability?.timezone||localZone()}}

export default function JourneyOfferings({journeyId}){
 const[items,setItems]=useState([]),[open,setOpen]=useState(false),[editingId,setEditingId]=useState(null),[form,setForm]=useState(empty),[error,setError]=useState(""),[saving,setSaving]=useState(false),[publishWarning,setPublishWarning]=useState(null);
 const load=()=>apiRequest(`/learning-journeys/${journeyId}/offerings`).then(data=>setItems((data.offerings||[]).filter(item=>TYPES[item.offering_type]))).catch(e=>setError(e.message));
 useEffect(()=>{load()},[journeyId]);
 const live=["ONE_TO_ONE","COHORT"].includes(form.offeringType);
 const group=form.offeringType==="COHORT";
 function create(){setEditingId(null);setForm(empty());setError("");setOpen(true)}
 function edit(item){setEditingId(item.id);setForm(fromItem(item));setError("");setOpen(true)}
 function selectType(offeringType){setForm(current=>({...current,offeringType,paymentModel:offeringType==="ONE_TO_ONE"?"FLEXIBLE":offeringType==="SELF_PACED"?"ONE_TIME":current.paymentModel==="FLEXIBLE"?"ONE_TIME":current.paymentModel,accessPolicy:offeringType==="SELF_PACED"?"LIFETIME":current.accessPolicy}))}
 function payload(){const orderedSlots=[...form.cohortSlots].sort((a,b)=>`${a.firstDate}${a.time}`.localeCompare(`${b.firstDate}${b.time}`)),firstSlot=orderedSlots[0],firstStartsAt=firstSlot?new Date(`${firstSlot.firstDate}T${firstSlot.time}:00`).toISOString():null,totalClasses=Number(form.cohortWeeks||0)*orderedSlots.length;const cohortConfiguration=form.offeringType==="COHORT"?{cohortId:form.cohortId||null,firstStartsAt,frequency:form.cohortFrequency,timezone:form.cohortTimezone,weeks:Number(form.cohortWeeks),slots:orderedSlots}:null;const settings=form.offeringType==="ONE_TO_ONE"?{bookingAvailability:{timezone:form.availabilityTimezone,slotIntervalMinutes:30,weekly:form.availabilityDays.map(day=>({day,start:form.availabilityStart,end:form.availabilityEnd}))}}:form.offeringType==="COHORT"?{cohortConfiguration}:{};const accessPolicy=form.offeringType==="SELF_PACED"?"LIFETIME":form.accessPolicy;return{...form,paymentModel:form.offeringType==="ONE_TO_ONE"?"FLEXIBLE":form.offeringType==="SELF_PACED"?"ONE_TIME":form.paymentModel,accessPolicy,priceAmount:Number(form.priceAmount||0),accessDurationDays:accessPolicy==="FIXED_DAYS"?Number(form.accessDurationDays)||null:null,sessionCount:form.offeringType==="COHORT"?totalClasses:Number(form.sessionCount)||null,sessionDurationMinutes:Number(form.sessionDurationMinutes)||null,capacity:Number(form.capacity)||null,startsAt:firstStartsAt,recurrenceRule:form.offeringType==="COHORT"?{frequency:form.cohortFrequency,interval:form.cohortFrequency==="BIWEEKLY"?2:1}:{},settings}}
 async function submit(event){
  event.preventDefault();setSaving(true);setError("");let createdOfferingId=null;
  try{
   if(form.offeringType==="COHORT"&&!form.cohortSlots.length)throw new Error("Add at least one recurring class time in the calendar.");
   const response=await apiRequest(editingId?`/offerings/${editingId}`:`/learning-journeys/${journeyId}/offerings`,{method:editingId?"PUT":"POST",body:JSON.stringify(payload())});
   const offering=response.offering;if(!editingId)createdOfferingId=offering.id;
   if(form.offeringType==="COHORT"&&!editingId){
    const orderedSlots=[...form.cohortSlots].sort((a,b)=>`${a.firstDate}${a.time}`.localeCompare(`${b.firstDate}${b.time}`)),firstStartsAt=new Date(`${orderedSlots[0].firstDate}T${orderedSlots[0].time}:00`).toISOString();
    const cohortResponse=await apiRequest(`/offerings/${offering.id}/cohorts`,{method:"POST",body:JSON.stringify({title:form.title,startsAt:firstStartsAt,capacity:Number(form.capacity),timezone:form.cohortTimezone,recurrenceRule:{frequency:form.cohortFrequency,interval:form.cohortFrequency==="BIWEEKLY"?2:1}})});
    for(const [index,slot] of orderedSlots.entries()){const slotStart=new Date(`${slot.firstDate}T${slot.time}:00`).toISOString();await apiRequest(`/cohorts/${cohortResponse.cohort.id}/session-series`,{method:"POST",body:JSON.stringify({title:`${form.title} · ${new Date(`${slot.firstDate}T${slot.time}`).toLocaleDateString(undefined,{weekday:"long"})}`,firstStartsAt:slotStart,durationMinutes:Number(form.sessionDurationMinutes),frequency:form.cohortFrequency,occurrenceCount:Number(form.cohortWeeks),timezone:form.cohortTimezone,slotIndex:index+1})});}
    await apiRequest(`/offerings/${offering.id}`,{method:"PUT",body:JSON.stringify({settings:{cohortConfiguration:{cohortId:cohortResponse.cohort.id,firstStartsAt,frequency:form.cohortFrequency,timezone:form.cohortTimezone,weeks:Number(form.cohortWeeks),slots:orderedSlots}}})});
   }else if(form.offeringType==="COHORT"&&form.cohortId){
    const orderedSlots=[...form.cohortSlots].sort((a,b)=>`${a.firstDate}${a.time}`.localeCompare(`${b.firstDate}${b.time}`)),firstStartsAt=new Date(`${orderedSlots[0].firstDate}T${orderedSlots[0].time}:00`).toISOString();
    await apiRequest(`/cohorts/${form.cohortId}`,{method:"PUT",body:JSON.stringify({title:form.title,startsAt:firstStartsAt,capacity:Number(form.capacity),timezone:form.cohortTimezone,recurrenceRule:{frequency:form.cohortFrequency,interval:form.cohortFrequency==="BIWEEKLY"?2:1}})});
    const seriesData=await apiRequest(`/cohorts/${form.cohortId}/session-series`),firstSeries=seriesData.series?.[0];
    if(firstSeries){const eventData=await apiRequest(`/session-series/${firstSeries.id}/events`),firstEvent=eventData.events?.[0];if(firstEvent&&new Date(firstEvent.starts_at).getTime()!==new Date(firstStartsAt).getTime())await apiRequest(`/calendar/events/${firstEvent.id}/scope`,{method:"PATCH",body:JSON.stringify({scope:"SERIES",startsAt:firstStartsAt})});}
   }
   setOpen(false);setEditingId(null);setForm(empty());load();
  }catch(requestError){if(createdOfferingId)try{await apiRequest(`/offerings/${createdOfferingId}`,{method:"DELETE"})}catch{}setError(requestError.message)}finally{setSaving(false)}
 }
 async function setStatus(item,status){if(status==="PUBLISHED"&&item.offering_type==="ONE_TO_ONE"){setPublishWarning(item);return}try{const cohortId=item.settings?.cohortConfiguration?.cohortId;if(item.offering_type==="COHORT"&&cohortId)await apiRequest(`/cohorts/${cohortId}`,{method:"PUT",body:JSON.stringify({status:status==="PUBLISHED"?"OPEN":"DRAFT"})});await apiRequest(`/offerings/${item.id}`,{method:"PUT",body:JSON.stringify({status})});load()}catch(requestError){setError(requestError.message)}}
 async function confirmPublish(){try{await apiRequest(`/offerings/${publishWarning.id}`,{method:"PUT",body:JSON.stringify({status:"PUBLISHED"})});setPublishWarning(null);load()}catch(requestError){setError(requestError.message)}}
 async function remove(item){if(!window.confirm(`Archive "${item.title}"?`))return;await apiRequest(`/offerings/${item.id}`,{method:"DELETE"});load()}
 return <section className="offers_workspace">
  <header className="offers_intro"><div><span>Monetize this Journey</span><h2>Experiences</h2><p>Offer the same reusable content with different payment and access rules.</p></div><button onClick={create}><i className="fa-solid fa-plus"/> Create experience</button></header>
  {error&&<div className="offers_alert">{error}</div>}
  <div className="offers_grid">{items.map(item=>{const meta=TYPES[item.offering_type],payment=PAYMENTS[item.payment_model]||PAYMENTS.ONE_TIME,access=ACCESS[item.access_policy]||ACCESS.LIFETIME;return <article className="offer_card" key={item.id}><header><div className={`offer_type_icon ${item.offering_type.toLowerCase()}`}><i className={`fa-solid ${meta.icon}`}/></div><span className={`offer_status ${item.status.toLowerCase()}`}>{item.status}</span></header><small>{meta.label}</small><h3>{item.title}</h3><p>{item.description||meta.hint}</p><div className="offer_price"><strong>{new Intl.NumberFormat(undefined,{style:"currency",currency:item.currency}).format(item.price_amount/100)}</strong><span>{item.payment_model==="PER_SESSION"?"per class":item.payment_model==="MONTHLY"?"per month":item.offering_type==="ONE_TO_ONE"?"per class":"complete price"}</span></div><div className="offer_policy_summary"><span><i className="fa-solid fa-money-check-dollar"/>{payment.label}</span><span><i className="fa-solid fa-key"/>{access.label}</span></div><div className="offer_facts">{item.session_duration_minutes&&<span><i className="fa-regular fa-clock"/>{item.session_duration_minutes} min</span>}{item.capacity&&<span><i className="fa-solid fa-users"/>{item.capacity} seats</span>}{item.offering_type==="COHORT"&&item.settings?.cohortConfiguration?.firstStartsAt&&<span><i className="fa-regular fa-calendar"/>{new Date(item.settings.cohortConfiguration.firstStartsAt).toLocaleDateString()}</span>}</div><footer><button onClick={()=>edit(item)}><i className="fa-solid fa-pen"/> Edit</button>{item.status!=="PUBLISHED"?<button onClick={()=>setStatus(item,"PUBLISHED")}>Publish</button>:<button onClick={()=>setStatus(item,"PAUSED")}>Pause</button>}<button className="danger" onClick={()=>remove(item)} aria-label="Archive"><i className="fa-solid fa-trash"/></button></footer></article>})}<button className="offer_add_card" onClick={create}><i className="fa-solid fa-plus"/><strong>Create another experience</strong><span>Self-paced, private classes or a new Cohort.</span></button></div>
  {open&&<div className="offer_modal_backdrop" onMouseDown={event=>event.target===event.currentTarget&&setOpen(false)}><form className="offer_modal" onSubmit={submit}><header><div><span>{editingId?"Edit experience":"New experience"}</span><h2>{editingId?"Update the commercial experience":"How do you want to teach?"}</h2></div><button type="button" onClick={()=>setOpen(false)}><i className="fa-solid fa-xmark"/></button></header>
   <div className="offer_type_picker">{Object.entries(TYPES).map(([type,meta])=><button type="button" className={form.offeringType===type?"selected":""} onClick={()=>selectType(type)} key={type}><i className={`fa-solid ${meta.icon}`}/><span><strong>{meta.label}</strong><small>{meta.hint}</small></span></button>)}</div>
   <section className="commercial_policy_section"><header><span><b>1</b><strong>How will students pay?</strong></span><small>Price meaning changes according to this choice.</small></header><div>{Object.entries(PAYMENTS).filter(([key])=>form.offeringType==="ONE_TO_ONE"?key==="FLEXIBLE":form.offeringType==="SELF_PACED"?key==="ONE_TIME":key!=="FLEXIBLE").map(([key,value])=><button type="button" className={form.paymentModel===key?"active":""} onClick={()=>setForm({...form,paymentModel:key,accessPolicy:key==="MONTHLY"&&form.accessPolicy==="LIFETIME"?"WHILE_ACTIVE":form.accessPolicy})} key={key}><i className={`fa-solid ${key==="MONTHLY"?"fa-arrows-rotate":key==="PER_SESSION"?"fa-calendar-day":"fa-wallet"}`}/><span><strong>{value.label}</strong><small>{value.hint}</small></span></button>)}</div></section>
   {form.offeringType==="SELF_PACED"?<section className="commercial_policy_section access"><header><span><b>2</b><strong>Content access</strong></span></header><div className="commercial_notice permanent"><i className="fa-solid fa-infinity"/><span><strong>Permanent access included</strong><small>A self-paced course is purchased once and remains in the learner's library for life.</small></span></div></section>:<section className="commercial_policy_section access"><header><span><b>2</b><strong>How long can they use the content?</strong></span></header><div>{Object.entries(ACCESS).filter(([key])=>!(form.paymentModel==="MONTHLY"&&key==="LIFETIME")).map(([key,value])=><button type="button" className={form.accessPolicy===key?"active":""} onClick={()=>setForm({...form,accessPolicy:key})} key={key}><i className={`fa-solid ${key==="LIFETIME"?"fa-infinity":key==="WHILE_ACTIVE"?"fa-link":"fa-hourglass-half"}`}/><span><strong>{value.label}</strong><small>{value.hint}</small></span></button>)}</div>{form.accessPolicy==="FIXED_DAYS"&&<label>Access duration in days<input required type="number" min="1" value={form.accessDurationDays} onChange={event=>setForm({...form,accessDurationDays:event.target.value})}/></label>}</section>}
   {form.offeringType==="ONE_TO_ONE"&&<section className="teacher_availability"><header><div><span>Weekly availability</span><h3>When can students book you?</h3></div><label>Timezone<input value={form.availabilityTimezone} onChange={event=>setForm({...form,availabilityTimezone:event.target.value})}/></label></header><div className="availability_days">{WEEKDAYS.map(([day,label])=><button type="button" className={form.availabilityDays.includes(day)?"active":""} onClick={()=>setForm({...form,availabilityDays:form.availabilityDays.includes(day)?form.availabilityDays.filter(value=>value!==day):[...form.availabilityDays,day]})} key={day}>{label}</button>)}</div><div className="availability_hours"><label>Available from<input type="time" value={form.availabilityStart} onChange={event=>setForm({...form,availabilityStart:event.target.value})}/></label><span>to</span><label>Available until<input type="time" value={form.availabilityEnd} onChange={event=>setForm({...form,availabilityEnd:event.target.value})}/></label></div><p><i className="fa-solid fa-circle-info"/> Students can only reserve at least 12 hours in advance.</p></section>}
   {form.offeringType==="COHORT"&&<section className="cohort_inline_setup"><header><div><span>Group schedule</span><h3>Create this Cohort now</h3><p>This experience represents one group. To open another group, create another Cohort experience.</p></div><i className="fa-solid fa-people-group"/></header><CohortScheduleBuilder slots={form.cohortSlots} weeks={form.cohortWeeks} frequency={form.cohortFrequency} timezone={form.cohortTimezone} onSlotsChange={cohortSlots=>setForm({...form,cohortSlots})} onWeeksChange={cohortWeeks=>setForm({...form,cohortWeeks})} onFrequencyChange={cohortFrequency=>setForm({...form,cohortFrequency})}/><div className="cohort_inline_grid compact"><label>Minutes per class<input required type="number" min="15" value={form.sessionDurationMinutes} onChange={event=>setForm({...form,sessionDurationMinutes:event.target.value})}/></label><label>Available seats<input required type="number" min="1" value={form.capacity} onChange={event=>setForm({...form,capacity:event.target.value})}/></label><label>Timezone<input required value={form.cohortTimezone} onChange={event=>setForm({...form,cohortTimezone:event.target.value})}/></label></div><div className="maze_classroom_notice"><i className="fa-solid fa-video"/><span><strong>Classes happen in Maze Studio</strong><small>Every selected weekly time receives its own recurring series and secure Maze Classroom.</small></span></div></section>}
   <label>Experience name<input required value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label><label>Description<textarea value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label>
   <div className="offer_form_grid"><label>{form.paymentModel==="MONTHLY"?"Price per month":form.paymentModel==="PER_SESSION"||form.offeringType==="ONE_TO_ONE"?"Price per class":"Complete price"}<input type="number" min="0" step="0.01" value={form.priceAmount} onChange={event=>setForm({...form,priceAmount:event.target.value})}/></label><label>Currency<select value={form.currency} onChange={event=>setForm({...form,currency:event.target.value})}><option>MXN</option><option>USD</option><option>EUR</option></select></label>{form.offeringType==="ONE_TO_ONE"&&<label>Minutes per class<input type="number" min="15" value={form.sessionDurationMinutes} onChange={event=>setForm({...form,sessionDurationMinutes:event.target.value})}/></label>}</div>
   {form.paymentModel==="PER_SESSION"&&<div className="commercial_notice"><i className="fa-solid fa-circle-info"/><span><strong>Students are charged for each scheduled class</strong><small>The schedule above determines every class included in this Cohort.</small></span></div>}
   <footer><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button type="submit" disabled={saving||form.offeringType==="ONE_TO_ONE"&&(!form.availabilityDays.length||form.availabilityStart>=form.availabilityEnd)}>{saving?"Saving…":editingId?"Save changes":"Create draft"}</button></footer>
  </form></div>}
  {publishWarning&&<div className="offer_modal_backdrop"><section className="offer_publish_warning"><i className="fa-solid fa-user-clock"/><span>Before you publish</span><h2>Students choose their class times</h2><p>They can buy a one-time package or a monthly weekly schedule. Every booking requires at least 12 hours of notice.</p><div><button onClick={()=>setPublishWarning(null)}>Not yet</button><button onClick={confirmPublish}>I understand · Publish</button></div></section></div>}
 </section>;
}
