const model=require("../models/calendarModel");
async function list(req,res,next){try{if(req.query.audience==="learner"||req.user.role!=="EDUCATOR")await require("../services/marketplaceService").reconcilePurchases(req.user.id);const from=req.query.from||new Date().toISOString();const to=req.query.to||new Date(Date.now()+31*86400000).toISOString();res.json({events:await model.list(req.user,from,to,req.query.audience)});}catch(e){next(e)}}
async function create(req,res,next){try{if(!req.body.title?.trim()||!req.body.startsAt||!req.body.endsAt){const e=new Error("Title, start and end are required");e.statusCode=400;throw e}res.status(201).json({event:await model.create(req.user.id,req.body)});}catch(e){next(e)}}
async function remove(req,res,next){try{const event=await model.remove(req.user.id,req.params.eventId);if(!event){const e=new Error("Event not found");e.statusCode=404;throw e}res.json({message:"Event deleted"});}catch(e){next(e)}}
async function confirmAttendance(req,res,next){try{if(typeof req.body.attended!=="boolean"){const e=new Error("attended must be true or false");e.statusCode=400;throw e}res.json(await model.confirmAttendance(req.user.id,req.params.eventId,req.body.attended));}catch(e){next(e)}}
async function participants(req,res,next){try{const rows=await model.participants(req.user.id,req.params.eventId);if(!rows)throw Object.assign(new Error("Calendar event not found"),{statusCode:404});res.json({students:rows})}catch(e){next(e)}}
async function inviteParticipant(req,res,next){try{if(!req.body.learnerProfileId)throw Object.assign(new Error("Choose a student"),{statusCode:400});res.status(201).json(await model.inviteParticipant(req.user.id,req.params.eventId,req.body.learnerProfileId))}catch(e){next(e)}}
async function removeParticipant(req,res,next){try{const removed=await model.removeParticipant(req.user.id,req.params.eventId,req.params.profileId);if(!removed)throw Object.assign(new Error("Invitation not found"),{statusCode:404});res.json({removed:true})}catch(e){next(e)}}
module.exports={list,create,remove,confirmAttendance,participants,inviteParticipant,removeParticipant};
