import { useEffect, useMemo, useState } from "react";
import StudioLayout from "../../layouts/studioLayout/StudioLayout";
import { apiRequest } from "../../../api/api";
import { useAuth } from "../../../context/AuthContext";
import RescheduleCalendar from "./RescheduleCalendar";
import "./Calendar.css";
import "./CalendarEnhancements.css";

const pad=(value)=>String(value).padStart(2,"0");
const dateKey=(date)=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;
const localInput=(date)=>`${dateKey(date)}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
const colors={LIVE_CLASS:"purple",ONE_TO_ONE:"blue",WEBINAR:"pink",OFFICE_HOURS:"green",CHALLENGE_DUE:"orange",CHALLENGE_RELEASE:"yellow",CUSTOM:"slate"};
function initialForm(){const start=new Date();start.setMinutes(Math.ceil(start.getMinutes()/30)*30,0,0);return{title:"",eventType:"LIVE_CLASS",startsAt:localInput(start),endsAt:localInput(new Date(start.getTime()+3600000)),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,learningJourneyId:"",meetingUrl:"",description:"",inviteAllJourney:true}}

export default function Calendar({learnerMode=false}){
 const {user}=useAuth();
 const [cursor,setCursor]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
 const [events,setEvents]=useState([]),[journeys,setJourneys]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [open,setOpen]=useState(false),[selectedEvent,setSelectedEvent]=useState(null),[meetingDraft,setMeetingDraft]=useState(""),[savingMeeting,setSavingMeeting]=useState(false),[requests,setRequests]=useState([]),[reschedule,setReschedule]=useState({startsAt:"",reason:""}),[rescheduleBusy,setRescheduleBusy]=useState(false),[form,setForm]=useState(initialForm);
 const range=useMemo(()=>({from:new Date(cursor.getFullYear(),cursor.getMonth(),1-cursor.getDay()),to:new Date(cursor.getFullYear(),cursor.getMonth()+1,8)}),[cursor]);
 const load=()=>{setLoading(true);setError("");Promise.all([apiRequest(`/calendar/events?from=${encodeURIComponent(range.from.toISOString())}&to=${encodeURIComponent(range.to.toISOString())}`),apiRequest("/calendar/reschedule-requests")]).then(([eventData,requestData])=>{setEvents(eventData.events||[]);setRequests(requestData.requests||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[range.from.getTime(),range.to.getTime()]);
 useEffect(()=>{if(!learnerMode)apiRequest("/learning-journeys").then(data=>setJourneys(data.journeys||[])).catch(()=>{})},[learnerMode]);
 const days=useMemo(()=>Array.from({length:42},(_,index)=>new Date(range.from.getFullYear(),range.from.getMonth(),range.from.getDate()+index)),[range.from]);
 const grouped=useMemo(()=>events.reduce((map,event)=>{(map[dateKey(new Date(event.starts_at))]??=[]).push(event);return map},{}),[events]);
 const todayEvent=useMemo(()=>{const items=(grouped[dateKey(new Date())]||[]).filter(event=>event.source==="EVENT"&&new Date(event.ends_at)>new Date()).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at));return items[0]||null},[grouped]);

 function showModal(block=false){setForm({...initialForm(),eventType:block?"BOOKING_BLOCK":"LIVE_CLASS",title:block?"Unavailable":""});setOpen(true)}
 function selectEvent(event){setSelectedEvent(event);setMeetingDraft(event.meeting_url||"");setReschedule({startsAt:"",reason:""})}
 async function saveMeeting(){setSavingMeeting(true);setError("");try{await apiRequest(`/calendar/events/${selectedEvent.id}/scope`,{method:"PATCH",body:JSON.stringify({scope:"FUTURE",meetingUrl:meetingDraft})});setSelectedEvent(null);load()}catch(requestError){setError(requestError.message)}finally{setSavingMeeting(false)}}
 async function proposeReschedule(){setRescheduleBusy(true);setError("");try{await apiRequest(`/calendar/events/${selectedEvent.id}/reschedule-requests`,{method:"POST",body:JSON.stringify({startsAt:new Date(reschedule.startsAt).toISOString(),reason:reschedule.reason})});setSelectedEvent(null);load()}catch(requestError){setError(requestError.message)}finally{setRescheduleBusy(false)}}
 async function decideReschedule(request,approve){const note=approve?"":window.prompt("Reason for declining (optional)")||"";setRescheduleBusy(true);setError("");try{await apiRequest(`/calendar/reschedule-requests/${request.id}/decision`,{method:"POST",body:JSON.stringify({approve,note})});load()}catch(requestError){setError(requestError.message)}finally{setRescheduleBusy(false)}}
 async function submit(event){event.preventDefault();setError("");try{const blocked=form.eventType==="BOOKING_BLOCK";await apiRequest("/calendar/events",{method:"POST",body:JSON.stringify({...form,eventType:blocked?"CUSTOM":form.eventType,metadata:blocked?{blocksBooking:true}:{},locationType:blocked?"NONE":"ONLINE",meetingProvider:blocked?"NONE":"MANUAL",learningJourneyId:blocked?null:form.learningJourneyId||null,meetingUrl:blocked?null:form.meetingUrl,inviteAllJourney:blocked?false:form.inviteAllJourney,startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString()})});setOpen(false);load()}catch(requestError){setError(requestError.message)}}
 function eventBlock(event){const content=<><b>{new Date(event.starts_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</b><span>{event.title}</span></>;const className=`calendar_event ${event.metadata?.blocksBooking?"blocked":colors[event.event_type]||"slate"}`;return learnerMode&&event.meeting_url?<a key={event.id} className={className} href={event.meeting_url} target="_blank" rel="noreferrer" title="Open class meeting">{content}</a>:<button type="button" key={event.id} className={className} onClick={()=>selectEvent(event)} title="View class details">{content}</button>}

 const content=<main className={`calendar_page ${learnerMode?"learner_calendar":""}`}>
  <header className="calendar_header"><div><span>{learnerMode?"My schedule":"Teaching schedule"}</span><h1>Calendar</h1><p>Classes, webinars, meetings and private booking availability.</p></div>{!learnerMode&&<div className="calendar_header_actions"><button className="block" onClick={()=>showModal(true)}><i className="fa-solid fa-lock"/> Block availability</button><button onClick={()=>showModal(false)}><i className="fa-solid fa-plus"/> Schedule event</button></div>}</header>
  <section className="calendar_toolbar"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><i className="fa-solid fa-chevron-left"/></button><div><h2>{cursor.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</h2><button onClick={()=>setCursor(new Date(new Date().getFullYear(),new Date().getMonth(),1))}>Today</button></div><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><i className="fa-solid fa-chevron-right"/></button></section>
  {error&&<div className="calendar_alert">{error}</div>}
  {requests.some(request=>request.status==="PENDING")&&<section className="calendar_reschedule_center"><header><div><span>Schedule changes</span><h2>Pending reschedule requests</h2></div><em>{requests.filter(request=>request.status==="PENDING").length} pending</em></header><div>{requests.filter(request=>request.status==="PENDING").map(request=><article key={request.id}><i className="fa-solid fa-calendar-arrow-down"/><div><strong>{request.title}</strong><small>Proposed by {request.requester_name}: {new Date(request.proposed_starts_at).toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short"})}</small>{request.reason&&<p>{request.reason}</p>}</div>{request.requested_to_user_id===user?.id?<span><button disabled={rescheduleBusy} onClick={()=>decideReschedule(request,false)}>Decline</button><button disabled={rescheduleBusy} onClick={()=>decideReschedule(request,true)}>Approve</button></span>:<em>Waiting for approval</em>}</article>)}</div></section>}
  {learnerMode&&todayEvent&&<section className="calendar_today_class"><div className="calendar_today_pulse"><i className="fa-solid fa-video"/></div><div><span>Your class today</span><h2>{todayEvent.title}</h2><p>{new Date(todayEvent.starts_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})} – {new Date(todayEvent.ends_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}{todayEvent.journey_title?` · ${todayEvent.journey_title}`:""}</p></div>{todayEvent.meeting_url?<a href={todayEvent.meeting_url} target="_blank" rel="noreferrer">Join class <i className="fa-solid fa-arrow-up-right-from-square"/></a>:<button type="button" onClick={()=>setSelectedEvent(todayEvent)}>View class details</button>}</section>}
  {loading?<div className="calendar_loading">Loading schedule…</div>:<section className="calendar_board"><div className="calendar_weekdays">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><span key={day}>{day}</span>)}</div><div className="calendar_days">{days.map(day=><article className={`${day.getMonth()!==cursor.getMonth()?"muted":""} ${dateKey(day)===dateKey(new Date())?"today":""}`} key={dateKey(day)}><time>{day.getDate()}</time><div>{(grouped[dateKey(day)]||[]).slice(0,3).map(eventBlock)}{(grouped[dateKey(day)]||[]).length>3&&<small>+{(grouped[dateKey(day)]||[]).length-3} more</small>}</div></article>)}</div></section>}
  <section className="calendar_legend">{[["purple","Class"],["blue","1:1"],["pink","Webinar"],["blocked","Unavailable"],["orange","Challenge due"]].map(([color,label])=><span key={label}><i className={color}/>{label}</span>)}</section>
  {open&&<div className="calendar_modal_backdrop" onMouseDown={event=>event.target===event.currentTarget&&setOpen(false)}><form className="calendar_modal" onSubmit={submit}><header><div><span>{form.eventType==="BOOKING_BLOCK"?"Private booking availability":"New calendar event"}</span><h2>{form.eventType==="BOOKING_BLOCK"?"Block unavailable time":"Schedule a class or meeting"}</h2></div><button type="button" onClick={()=>setOpen(false)}><i className="fa-solid fa-xmark"/></button></header>{form.eventType==="BOOKING_BLOCK"&&<div className="calendar_block_notice"><i className="fa-solid fa-lock"/><span><strong>Students cannot book this period</strong><small>This also prevents recurring 1:1 packages from overlapping it.</small></span></div>}<label>Title<input required value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label><div className="calendar_form_grid">{form.eventType!=="BOOKING_BLOCK"&&<label>Event type<select value={form.eventType} onChange={event=>setForm({...form,eventType:event.target.value})}><option value="LIVE_CLASS">Live class</option><option value="ONE_TO_ONE">1:1 session</option><option value="WEBINAR">Webinar</option><option value="OFFICE_HOURS">Office hours</option><option value="CUSTOM">Other</option></select></label>}{form.eventType!=="BOOKING_BLOCK"&&<label>Learning Journey<select value={form.learningJourneyId} onChange={event=>setForm({...form,learningJourneyId:event.target.value})}><option value="">No Journey</option>{journeys.map(journey=><option value={journey.id} key={journey.id}>{journey.title}</option>)}</select></label>}<label>Starts<input type="datetime-local" value={form.startsAt} onChange={event=>setForm({...form,startsAt:event.target.value})} required/></label><label>Ends<input type="datetime-local" value={form.endsAt} onChange={event=>setForm({...form,endsAt:event.target.value})} required/></label></div>{form.eventType!=="BOOKING_BLOCK"&&<label>Meeting link<input type="url" value={form.meetingUrl} onChange={event=>setForm({...form,meetingUrl:event.target.value})}/></label>}<label>{form.eventType==="BOOKING_BLOCK"?"Private note":"Description"}<textarea value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label><footer><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button type="submit">{form.eventType==="BOOKING_BLOCK"?"Block this time":"Create event"}</button></footer></form></div>}
  {selectedEvent&&<div className="calendar_modal_backdrop" onMouseDown={event=>event.target===event.currentTarget&&setSelectedEvent(null)}><section className="calendar_class_details"><header><div><span>Scheduled class</span><h2>{selectedEvent.title}</h2></div><button type="button" onClick={()=>setSelectedEvent(null)}><i className="fa-solid fa-xmark"/></button></header><div className="calendar_class_time"><i className="fa-regular fa-calendar"/><span><strong>{new Date(selectedEvent.starts_at).toLocaleDateString(undefined,{dateStyle:"full"})}</strong><small>{new Date(selectedEvent.starts_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})} – {new Date(selectedEvent.ends_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small></span></div>{selectedEvent.description&&<p>{selectedEvent.description}</p>}{!learnerMode?<div className="calendar_meeting_editor"><label>Meet or Zoom link<input type="url" value={meetingDraft} onChange={event=>setMeetingDraft(event.target.value)} placeholder="https://meet.google.com/…"/></label><button type="button" onClick={saveMeeting} disabled={savingMeeting}>{savingMeeting?"Saving…":"Save for this and future classes"}</button></div>:selectedEvent.meeting_url?<a href={selectedEvent.meeting_url} target="_blank" rel="noreferrer">Join class <i className="fa-solid fa-arrow-up-right-from-square"/></a>:<div className="calendar_link_pending"><i className="fa-solid fa-clock"/><span><strong>Meeting link pending</strong><small>Your educator has not added the meeting link yet. It will appear on this block when available.</small></span></div>}{selectedEvent.event_type==="ONE_TO_ONE"&&<div className="calendar_reschedule_form"><span>Request a different time</span><RescheduleCalendar eventId={selectedEvent.id} value={reschedule.startsAt} onChange={startsAt=>setReschedule({...reschedule,startsAt})}/><label>Reason (optional)<textarea value={reschedule.reason} onChange={event=>setReschedule({...reschedule,reason:event.target.value})} placeholder="Tell the other person why you need to reschedule."/></label><button type="button" disabled={rescheduleBusy||!reschedule.startsAt} onClick={proposeReschedule}>{rescheduleBusy?"Sending…":"Send reschedule request"}</button><small>The class changes only after the other person approves.</small></div>}</section></div>}
 </main>;
 return learnerMode?content:<StudioLayout>{content}</StudioLayout>;
}
