import {useEffect,useRef,useState} from "react";
import "./RichTextEditor.css";
const escapeHtml=value=>String(value||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const safeUrl=value=>/^https?:\/\//i.test(String(value||""))?String(value):"";
const styleOf=run=>[run.color&&`color:${run.color}`,run.backgroundColor&&`background-color:${run.backgroundColor}`,run.fontSize&&`font-size:${run.fontSize}px`,run.bold&&"font-weight:700",run.italic&&"font-style:italic",run.underline&&"text-decoration:underline"].filter(Boolean).join(";");
function runsToHtml(runs){return(runs||[]).map(run=>run.type==="image"&&safeUrl(run.url)?`<img src="${escapeHtml(run.url)}" alt="${escapeHtml(run.alt)}" style="width:${Math.min(800,Math.max(24,Number(run.width)||180))}px;max-width:100%;vertical-align:middle">`:(()=>{const body=escapeHtml(run.text).replaceAll("\n","<br>");const styled=`<span style="${styleOf(run)}">${body}</span>`;return safeUrl(run.link)?`<a href="${escapeHtml(run.link)}">${styled}</a>`:styled})()).join("")}
function readRuns(root){
 const output=[];
 function push(text,state){if(!text)return;const clean={text,...state},previous=output.at(-1);if(previous&&previous.type!=="image"&&JSON.stringify({...clean,text:""})===JSON.stringify({...previous,text:""}))previous.text+=text;else output.push(clean)}
 function walk(node,state={}){if(node.nodeType===Node.TEXT_NODE){push(node.nodeValue,state);return}if(node.nodeType!==Node.ELEMENT_NODE)return;const tag=node.tagName,next={...state},style=node.style;if(tag==="IMG"){const url=safeUrl(node.getAttribute("src"));if(url)output.push({type:"image",url,alt:node.getAttribute("alt")||"",width:Math.min(800,Math.max(24,parseInt(style.width,10)||180))});return}if(tag==="B"||tag==="STRONG"||style.fontWeight==="bold"||Number(style.fontWeight)>=600)next.bold=true;if(tag==="I"||tag==="EM"||style.fontStyle==="italic")next.italic=true;if(tag==="U"||style.textDecoration.includes("underline"))next.underline=true;if(style.color)next.color=style.color;if(style.backgroundColor)next.backgroundColor=style.backgroundColor;if(style.fontSize)next.fontSize=parseInt(style.fontSize,10)||undefined;if(tag==="FONT"){if(node.color)next.color=node.color;if(node.size)next.fontSize={1:10,2:13,3:16,4:18,5:24,6:32,7:40}[node.size]}if(tag==="A")next.link=safeUrl(node.getAttribute("href"));if(tag==="BR"){push("\n",state);return}const block=["DIV","P"].includes(tag);if(block&&output.length&&output.at(-1).type!=="image"&&!output.at(-1).text.endsWith("\n"))push("\n",state);node.childNodes.forEach(child=>walk(child,next));if(block&&output.length&&output.at(-1).type!=="image"&&!output.at(-1).text.endsWith("\n"))push("\n",state)}
 root.childNodes.forEach(node=>walk(node));return output.length?output:[{text:""}];
}
export default function RichTextEditor({content,onChange,baseStyle}){
 const ref=useRef(null),rangeRef=useRef(null),[size,setSize]=useState(16),[color,setColor]=useState("#111827"),[highlight,setHighlight]=useState("#fff59d");
 useEffect(()=>{if(ref.current)ref.current.innerHTML=runsToHtml(Array.isArray(content.richText)?content.richText:[{text:content.text||""}])},[]);
 function remember(){const selection=window.getSelection();if(selection?.rangeCount&&ref.current?.contains(selection.anchorNode))rangeRef.current=selection.getRangeAt(0).cloneRange()}
 function restore(){if(!rangeRef.current)return;const selection=window.getSelection();selection.removeAllRanges();selection.addRange(rangeRef.current)}
 function emit(){if(!ref.current)return;const richText=readRuns(ref.current);onChange({text:richText.map(run=>run.text||"").join(""),richText});remember()}
 function command(name,value=null){restore();ref.current?.focus();document.execCommand(name,false,name==="fontSize"?"7":value);if(name==="fontSize")ref.current.querySelectorAll('font[size="7"]').forEach(node=>{node.removeAttribute("size");node.style.fontSize=`${value}px`});emit()}
 function link(){const url=window.prompt("Link URL (https://…)");if(url&&safeUrl(url))command("createLink",url)}
 function image(){const url=window.prompt("Public image URL (https://…)");if(!safeUrl(url))return;const width=Math.min(800,Math.max(24,Number(window.prompt("Image width in pixels","180"))||180));restore();ref.current?.focus();document.execCommand("insertImage",false,url);const images=ref.current.querySelectorAll(`img[src="${CSS.escape(url)}"]`),node=images[images.length-1];if(node){node.style.width=`${width}px`;node.style.maxWidth="100%";node.style.verticalAlign="middle";node.alt=window.prompt("Alternative text","")||""}emit()}
 return <div className="rich_text_workspace"><div className="rich_text_toolbar" onMouseUp={remember}><button type="button" onMouseDown={event=>event.preventDefault()} onClick={()=>command("bold")} title="Bold"><i className="fa-solid fa-bold"/></button><button type="button" onMouseDown={event=>event.preventDefault()} onClick={()=>command("italic")} title="Italic"><i className="fa-solid fa-italic"/></button><button type="button" onMouseDown={event=>event.preventDefault()} onClick={()=>command("underline")} title="Underline"><i className="fa-solid fa-underline"/></button><label>Size<select value={size} onMouseDown={remember} onChange={event=>{const value=Number(event.target.value);setSize(value);command("fontSize",value)}}>{[12,14,16,18,20,24,28,32,40,48,56,64].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label title="Text color"><i className="fa-solid fa-font"/><input type="color" value={color} onMouseDown={remember} onChange={event=>{setColor(event.target.value);command("foreColor",event.target.value)}}/></label><label title="Highlight"><i className="fa-solid fa-highlighter"/><input type="color" value={highlight} onMouseDown={remember} onChange={event=>{setHighlight(event.target.value);command("hiliteColor",event.target.value)}}/></label><button type="button" onMouseDown={event=>event.preventDefault()} onClick={link} title="Add link"><i className="fa-solid fa-link"/></button><button type="button" onMouseDown={event=>event.preventDefault()} onClick={image} title="Insert image here"><i className="fa-solid fa-image"/></button><button type="button" onMouseDown={event=>event.preventDefault()} onClick={()=>command("removeFormat")} title="Clear selection formatting"><i className="fa-solid fa-eraser"/></button></div><div ref={ref} className="rich_text_canvas" contentEditable suppressContentEditableWarning style={baseStyle} onInput={emit} onMouseUp={remember} onKeyUp={remember} data-placeholder="Write your content…"/></div>;
}
